name: "Continuous Deployment - DEV"
on:
  push:
    branches:
      - dev
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: austral-tricolor
          password: ${{ secrets.DOCKER_PACKAGES_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/tricolor-austral/ingsis-printscript-ui:latest
          build-args: |
            "USERNAME=${{ secrets.PUBLISH_USERNAME }}"
            "TOKEN=${{ secrets.DOCKER_PACKAGES_SECRET }}"

          push: true
